version: "3.9"

services:
  bot:
    container_name: ChatGPTSlackBot
    volumes:
      - ./bot:/bot
    build:
      context: ./bot
      args:
        SLACK_APP_TOKEN: ${SLACK_APP_TOKEN}
        SLACK_BOT_TOKEN: ${SLACK_BOT_TOKEN}
        SERVER_URL: ${SERVER_URL}
        SERVER_PORT: ${SERVER_PORT}
      dockerfile: Dockerfile
    environment:
      - SLACK_APP_TOKEN=${SLACK_APP_TOKEN}
      - SLACK_BOT_TOKEN=${SLACK_BOT_TOKEN}
      - SERVER_URL=${SERVER_URL}
      - SERVER_PORT=${SERVER_PORT}
